[package]
name = "auth"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
domain = { path = "../domain" }
jsonwebtoken.workspace = true
serde.workspace = true
sha2.workspace = true
hex.workspace = true
uuid.workspace = true
