[package]
name = "platform"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true


[dependencies]
async-trait = "0.1"
chrono.workspace = true
dotenvy.workspace = true
hex.workspace = true
hmac.workspace = true
jsonwebtoken.workspace = true
oxana.workspace = true
redis = { workspace = true, features = ["aio", "tokio-comp"] }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[[bin]]
name = "migrator"
path = "src/bin/migrator.rs"
