[package]
name = "index"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
domain = { path = "../domain" }
models = { path = "../models" }
reqwest.workspace = true
serde_json.workspace = true
uuid.workspace = true
