[package]
name = "retention"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
dotenvy.workspace = true
platform = { path = "../platform" }
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
platform = { path = "../platform" }
uuid.workspace = true
