[package]
name = "retention"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
dotenvy.workspace = true
runtime = { path = "../runtime" }
sqlx.workspace = true
storage = { path = "../storage" }
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
domain = { path = "../domain" }
storage = { path = "../storage", features = ["first-launch-migration"] }
uuid.workspace = true
