[package]
name = "migrator"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dotenvy.workspace = true
runtime = { path = "../runtime" }
storage = { path = "../storage", features = ["first-launch-migration"] }
tokio.workspace = true
tracing.workspace = true
